[package]
name = "custom-car-manager"
version = "2.0.0-SNAPSHOT"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = { version = "1.3.8", features = ["fltk-bundled"] }
fltk-theme = { version = "0.4" }

[build-dependencies]
fl2rust = "0.4"
