[package]
name = "custom-car-manager"
version = "2.0.0-SNAPSHOT"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = { git = "https://github.com/linebender/druid.git" }

[profile.release]
strip = true
lto = true
