name: Build

on: [ push, pull_request ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            suffix: ''
            name: Linux
          - os: windows-latest
            suffix: .exe
            name: Windows
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Cache
        uses: Swatinem/rust-cache@v2

      - name: Install Linux Dependencies
        if: ${{ runner.os == 'Linux' }}
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev libpango1.0-dev librust-alsa-sys-dev

      - name: Build
        run: cargo build --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: custom-car-manager-${{ matrix.name }}
          path: target/release/dv-content-manager${{ matrix.suffix }}

  code-style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Setup Cache
        uses: Swatinem/rust-cache@v2

      - name: Install Linux Dependencies
        if: ${{ runner.os == 'Linux' }}
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev libpango1.0-dev librust-alsa-sys-dev

      - name: Check Code Style
        run: cargo clippy -- -D warnings
